
<!DOCTYPE html>
<!--[if (gt IE 9)|!(IE)]><!--> <html class="no-js" lang="zh-cn"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <!-- www.phpied.com/conditional-comments-block-downloads/ -->
    <!-- Always force latest IE rendering engine
         (even in intranet) & Chrome Frame
         Remove this if you use the .htaccess -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--  Mobile Viewport Fix
          j.mp/mobileviewport & davidbcalhoun.com/2010/viewport-metatag
          device-width: Occupy full width of the screen in its current orientation
          initial-scale = 1.0 retains dimensions instead of zooming out if page height > device height
          user-scalable = yes allows the user to zoom in -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>itoshichannel</title>
    <!-- http://dev.w3.org/html5/markup/meta.name.html -->
    <meta name="application-name" content="itoshichannel">
    <!-- Speaking of Google, don't forget to set your site up:
         http://google.com/webmasters -->
    <meta name="google-site-verification" content="">
    <!-- include stylesheets -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="/itoshichannel/static/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="/itoshichannel/static/css/web2py-bootstrap4.css"/>
    <link rel="shortcut icon" href="/itoshichannel/static/images/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" href="/itoshichannel/static/images/favicon.png">
    <!-- All JavaScript at the bottom, except for Modernizr which enables
         HTML5 elements & feature detects -->
    <script src="/itoshichannel/static/js/modernizr-2.8.3.min.js"></script>
    <!-- Favicons -->
    <script type="text/javascript"><!--
    // These variables are used by the web2py_ajax_init function in web2py_ajax.js (which is loaded below).
    var w2p_ajax_confirm_message = "\u786e\u5b9a\u8981\u5220\u9664\u8be5\u5bf9\u8c61\u4e48\uff1f";
var w2p_ajax_disable_with_message = "Working...";
var w2p_ajax_date_format = "%Y-%m-%d";
var w2p_ajax_datetime_format = "%Y-%m-%d %H:%M:%S";
var ajax_error_500 = "An error occured, please \u003ca href=\"/itoshichannel/default/index\"\u003ereload\u003c/a\u003e the page";

    //--></script>

<meta name="author" content="Your Name &lt;you@example.com&gt;" />
<meta name="description" content="a cool new app" />
<meta name="keywords" content="&lt;map object at 0x000001A227924E48&gt;" />
<meta name="generator" content="Web2py Web Framework" />
<script src="/itoshichannel/static/js/jquery.js" type="text/javascript"></script><link href="/itoshichannel/static/css/calendar.css" rel="stylesheet" type="text/css" /><script src="/itoshichannel/static/js/calendar.js" type="text/javascript"></script><script src="/itoshichannel/static/js/web2py.js" type="text/javascript"></script>
 <!-- this includes jquery.js, calendar.js/.css and web2py.js -->
    
  </head>
  <body>
    <div class="w2p_flash alert alert-dismissable"></div>
    <!-- Navbar ======================================= -->
    <nav class="navbar navbar-light navbar-expand-md bg-faded bg-dark navbar-dark justify-content-center">
       <a href="http://web2py.com" class="navbar-brand d-flex w-50 mr-auto">itoshichannel</a>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
       <div class="navbar-collapse collapse w-100" id="navbarNavDropdown">
         <ul class="navbar-nav w-100 justify-content-center">
          
          
          <li class="nav-item ">
            <a class="nav-link" href="/itoshichannel/default/index">love</a>
          </li>
          
          
        </ul>
         <form class="form-inline my-2 my-lg-0">
             <input class="form-control mr-sm-2" type="text" placeholder="Search">
         </form>
        
        <ul class="nav navbar-nav ml-auto w-100 justify-content-end">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              LOGIN
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              
              <a class="dropdown-item" href="/itoshichannel/default/user/login">登录</a>
              
              <a class="dropdown-item" href="/itoshichannel/default/user/register">Sign up</a>
              
              
              <a class="dropdown-item" href="/itoshichannel/default/user/retrieve_password">忘记密码</a>
              
              
            </div>
          </li>
        </ul>
        
      </div>
    </nav>

    <!-- Masthead ===================================== -->
    
    
    <!-- Main ========================================= -->
    <!-- Begin page content -->
    <div class="container-fluid main-container">
      
 
<h2>你觉得你的选择可以影响一个人的人生吗？</h2><p>●是 ○不是</p><h2>loading……</h2><h2>所以你想决定我的人生，对吗？</h2><p>●是 ○不是</p><h2>loading……</h2><h2>你现在感到害怕吗？你会在想这个网站是怎么回事吗？</h2><p>●是 ○不是</p><h2>loading……</h2><h2>我好像失忆了。我现在只记得我的名字。你知道我的事情吗？</h2><p>○知道 ●不知道</p><h2>loading……</h2><h2>……</h2><h2>loading……</h2><h2>……我会自己想办法的。</h2><h2>loading……</h2><h2>再见。</h2><p>以后别随便点进不知名网站。</p><div class="w2p_wiki_tags"><a href="/itoshichannel/default/index/_search?q=%3A%28">:(</a></div>

      
    </div>

     <!-- this is default footer -->
    <footer class="footer container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="copyright pull-left">版权所有 &#169; 2024</div>
          <div id="poweredBy" class="pull-right">
            基于下列技术构建：
            <a href="http://www.web2py.com/">web2py</a>
          </div>
        </div>
      </div>
    </footer>
    
    <!-- The javascript =============================== -->
    <script src="/itoshichannel/static/js/bootstrap.bundle.min.js"></script>
    <script src="/itoshichannel/static/js/web2py-bootstrap4.js"></script>
    
    
  </body>
</html>
